version: '3.8'

services:
  pdp-db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pdp-network

  pdp-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    env_file:
      - ".env"
    depends_on:
      - pdp-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pdp-network

  pdp-minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "7000:9000"
      - "7001:7001"
    env_file:
      - ".env"
    volumes:
      - ./data/minio:/data
    networks:
      - pdp-network
    command: server /data --console-address ":7001"

  pdp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ".env"
    depends_on:
      - pdp-db
      - pdp-minio
    environment:
      POSTGRESQL_DSN: ${POSTGRESQL_DSN}
    volumes:
      - .:/app
    networks:
      - pdp-network

networks:
  pdp-network:
    name: pdp-network
    driver: bridge

volumes:
  postgres_data:
